# Generated by Django 5.0.6 on 2024-05-23 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.CharField(choices=[('solgas', 'Solgas'), ('llamagas', 'Llamagas'), ('newgas', 'Newgas')], max_length=10)),
                ('dirección', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Balones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valvula', models.CharField(choices=[('premium', 'Premium'), ('regular', 'Regular')], max_length=10)),
                ('peso', models.CharField(choices=[('10kg', '10kg'), ('15kg', '15kg')], max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gassmart.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('dirección', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gassmart.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('consumo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=6)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gassmart.usuario')),
            ],
        ),
    ]
